BUILD_SCRIPT_DIR="$(cd $(dirname $0); pwd)"
PROJECT_PATH="${BUILD_SCRIPT_DIR}/../../../../.."
XCCONFIG_PATH="${BUILD_SCRIPT_DIR}"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/vendor/glsl-optimizer/projects/xcode5/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/vendor/libSpine/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/vendor/libKtx/proj.ios/build/xcode/ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/vendor/libTinyxml2/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/vendor/protobuf-2.6.1/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/vendor/jsoncpp/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/framework/libCommon/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/framework/libPlatform/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/externals/engine/client/framework/libUi/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/common/libMsg/client/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/examples/libVideoPoker/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/examples/libSlotMachine/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/examples/libPoker/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/examples/libCasino/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/examples/libBlackjack/proj.ios/"
cp "${BUILD_SCRIPT_DIR}/build-dir.xcconfig" "${PROJECT_PATH}/client/examples/SlotMachine/proj.ios/"