<?xml version="1.0" encoding="UTF-8"?>
<TweenTimeline id="xTween" TimeScale="1" TotalLoop="-1" Delay="0" IsSkippable="0" RemoveChild="1" IsExit="0" IsReferenceParent="1" ReferenceName="" IsLinearTimeline="1" controlpoints="">
    <UseTimeLimit value="1"/>
    <TimeLimit value="-1"/>
    <HideBeforeStart value="0"/>
    <HideAfterStop value="0"/>
    <TargetWindowId value="param#2"/>
    <TweenScript value="t=0.000000,sy=0.900000|t=0.500000,sy=1.000000|t=1.000000,sy=0.900000|t=1.500000,sy=1.000000|t=2.000000,sy=0.900000|t=0.000000,sx=1.100000|t=0.500000,sx=1.000000|t=1.000000,sx=1.100000|t=1.500000,sx=1.000000|t=2.000000,sx=1.100000|"/>
</TweenTimeline>
