/*!
* \file CvsConfig.h
* \date 2-7-2013 13:37:06
*
*
* \author zjhlogo (zjhlogo@gmail.com)
*/
#pragma once

#define ENGINE_VERSION_MAJOR 1
#define ENGINE_VERSION_MINOR 2
#define ENGINE_VERSION_PATCH 15
#define ENGINE_VERSION  (ENGINE_VERSION_MAJOR << 16 | ENGINE_VERSION_MINOR << 8 | ENGINE_VERSION_PATCH)
#define BIND_ENGINE_VERSION(MAJOR, MINOR, PATCH) (MAJOR<<16 | MINOR<<8 | PATCH)

#define CASINO_VERSION_MAJOR 1
#define CASINO_VERSION_MINOR 4
#define CASINO_VERSION_PATCH 0
#define CASINO_VERSION  (CASINO_VERSION_MAJOR << 16 | CASINO_VERSION_MINOR << 8 | CASINO_VERSION_PATCH)
#define BIND_CASINO_VERSION(MAJOR, MINOR, PATCH) (MAJOR<<16 | MINOR<<8 | PATCH)